spring:
  cloud:
    function:
      definition: publishProduct
    stream:
      bindings:
        publish-out-0:
          binder: local-solace
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://your-service.com:55555
                msgVpn: VPNName
                clientUsername: 
                clientPassword: 
server:
  port: 8093