spring:
  cloud:
    function:
      definition: publishOrder
    stream:
      bindings:
        publish-out-0:
          binder: local-solace
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: localhost:55554
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
server:
  port: 8093